#!/bin/bash

root="/tmp/zfind"

go run scripts/run_test_prep.go

cd $root/root/time
zip -r ../day/time.zip *
7z a ../year/time.7z *

cd $root/root/thing
tar -cvf ../way/thing.tar *
tar -czvf ../year/thing.tar.gz *
tar -czvf ../year/thing.tgz *
tar -cjvf ../people/thing.tar.bz2 *
tar -cjvf ../people/thing.tbz2 *

cd $root/root
rm -rf $root/root/time $root/root/thing
mv $root/root/people $root/people
ln -s ../people people

find -L | wc -l
