#!/bin/bash

export TZ='UTC'
root="/tmp/zfind"

go run scripts/run_test_prep.go

cd $root/root/time
zip -r ../day/time.zip *
7z a ../year/time.7z *
rm -rf $root/root/time

cd $root/root/thing
tar -cvf ../way/thing.tar *
tar -czvf ../year/thing.tar.gz *
tar -czvf ../year/thing.tgz *
tar --bzip2 -cvf ../people/thing.tar.bz2 *
tar --bzip2 -cvf ../people/thing.tbz2 *
tar --xz -cvf ../people/thing.tar.xz *
tar --xz -cvf ../people/thing.txz *
rm -rf $root/root/thing

cd $root/root
mv $root/root/people $root/people
ln -s ../people people
ln -s ../../people/face/office-door.pdf day/friend/party-result.png
find -L | wc -l
